"""exchange rates

Revision ID: 7af9dd7b99bb
Revises: a3363d6ff11d
Create Date: 2023-12-16 01:51:55.174694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af9dd7b99bb'
down_revision: Union[str, None] = 'a3363d6ff11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
